### ISSUE TITLE
¨dockerizePip: true¨ in Ubuntu 16.04 does not work (docker)

### ISSUE THREAD

**Issue by fadonoso** [UnitedIncome/serverless-python-requirements#158]
Hi there,
I have my project in MacOS and works really good, the docker image was called and everything was packaged fine. However, in my ubuntu 16.04 can not reach the docker image. I get this error:

> invalid reference format

I'm using the exact serverless.yml ( 'except for this change: dockerizePip: true'), so it is not that I´m using upper cases or something like that. 

Someone has crossed with this issue before?

Thanks

**Comment by dschep** [comment]
Glad you got it working! Yeah, real globally installed node is always a pain. and an especially bad idea given the recent `sudo npm` chown bugs. I always use nvm.

Just a note, if you're on 64 bit linux and your binarydependencies are available as manylinux wheels (things like numpy & psycopg[now as `psycopg-binary`])), you don't need docker. you can use the special value of `non-linux` for the `dockerizePip` option to skip using docker on linux machines, We use this option at @UnitedIncome so that mac users(almost all the developers) use docker, but CI and linux devs (just me) don't.
