### ISSUE TITLE
Problem with symlinks

### ISSUE THREAD

**Issue by Govinda-Fichtner** [UnitedIncome/serverless-python-requirements#23]
serverless-python-requirments version: 2.1.1
serverless version: 1.11

I have a serverless project based on python with the following directory structure:

/lib
/tests

and also have a requirements.txt with a package called 'chargebee'
This package includes a folder called 'tests'.

When this plugin creates symlinks in the root folder of the serverless project it raises an exception at 

https://github.com/UnitedIncome/serverless-python-requirements/blob/v2.1.1/index.js#L90

This leads to many left-over symlinks lying around.

To prevent this error wouldn't it be much nicer to create the symlinks in a separate temp-folder that even with an exception gets cleaned up afterwards?

Thus we would not have any problems with folders that are named the same in the .requirements folder and in the root folder of the serverless project.

**Comment by dschep** [comment]
The reason for linking to the root of the project is so that you don't have to add a directory to your `sys.path`. It looks like chargebee uses `find_packages()` with out omitting tests. I imagine this causes problems in other environments as well. I've taken the liberty of filing chargebee/chargebee-python#17

To use chargebee with this plugin I suggest using the [Zip option](https://github.com/UnitedIncome/serverless-python-requirements#dealing-with-lambdas-size-limitations) meant for dealing with size limitations, but also would work in this case because it doesn't simlink the libs. (tho, there might be an issue when it tires to unzip, so add tests to your package exclude serverless option.)
