### ISSUE TITLE
Add proper windows CI test coverage

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#249]
as #247 and #248 make obvious, testing on windows machines is not part of the usual release flow. This should change, but I'm not sure how to best go about running the bats test suite on windows or if it should be ported(not preferable, since then you have to maintain multiple test suites)

Also, it would be of interest to run this the various ways you can run it on windows (now of course, some of these make it much easier to use bats, eg when using WSL):
 * vanilla windows + docker for windows
 * vanilla windows + docker toolbox
 * WSL + "wsl" docker
 * WSL + docker for windows
 * cygwin + docker for windows
 * more? less? windows is so complicated.

CCing those I know to be windows-based users&contributors: @kichik @heri16 @vecchp @hubbins @ajshukury @lucasnp (others? If you know, plz tag them)

**Comment by hubbins** [comment]
IMHO, "windows + docker for windows" is going to cover almost all Windows users.  I don't think there are many docker toolbox users anymore.  WSL should essentially be covered by your existing tests, since there are no drive letters (/mnt/c and /mnt/d are used for C: and D: for example).  If there are users that fall into the docker toolbox or cygwin buckets, they should speak up if they exist.  Or focus on those users later.

**Comment by kichik** [comment]
I use Docker Toolbox. On one computer because I didn't want to pay extra for Windows Pro, and on another computer because my work requires me to have VirtualBox there. Docker for Windows is sadly still a limitation for some. I strongly believe we should support both.

**Comment by dschep** [comment]
@kichik, note, regardless of it being tested or not, docker toolbox won't be dropped. even windows with docker for  windows tests benefits windows with docker toolbox :smile:

**Comment by hubbins** [comment]
@kichik I'm such making a suggestion around prioritization, not whether to support or not.
