### ISSUE TITLE
unzip_requirements.py pointing to wrong directory when using module in serverless.yml

### ISSUE THREAD

**Issue by robwrighty0** [UnitedIncome/serverless-python-requirements#257]
We are using multiple lambda functions with a structure as follows:

├── serverless.yml
├── requirements.txt
├── function1
│      ├── requirements.txt
│      └── handler2.py
└── function2
      ├─── requirements.txt
      └─── handler2.py

The top level requirements.txt is used by our CI server. In our serverless.yml, we are using the module prefix to package lambda functions individually (see below). We are finding however, that unzip_requirements.py is not finding the zipped libraries, since these are no longer located at the top level of the zip (as indicated by line 17 of unzip_requirements.py), but at the lambda function level. I have created a temporary local fix to this problem, but am wondering if anyone understands why this is happening?

package:
  individually: true
  exclude:
    - ./**
custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    dockerSsh: true
    zip: true
    noDeploy:
      - pytest

plugins:
  - serverless-python-requirements

functions:
  function1:
    module: function1
    handler: handler1
    package:
      include:
       ***various imports***
  function2:
    module: function2
    handler: handler2
    package:
      include:
       ***various imports***

**Comment by miketheman** [comment]
@robwrighty0 Thanks for reporting. We're going through older issues to sort out what's currently still open.
The behavior has changed a bit since you've reported this, so I'm going to close out this issue. If there's still a problem, please open a new issue (feel free to reference this one) with the current version details and yml structure. Thanks, and sorry it took so long!
