### ISSUE TITLE
Take full advantage of Lambda's size limitations

### ISSUE THREAD

**Issue by izhangzhihao** [UnitedIncome/serverless-python-requirements#492]
according to the AWS lambda doc deployment package size has a 250 MB (unzipped, including layers) limit and the `/tmp` directory storage has 512 MB. Can we split the dependencies into two parts if the unzipped `.requirements.zip` is bigger than 512 MB. For example if we have 600MB dependencies, we can just put ~512 MB into `/tmp`, and other 90MB in somewhere else.

**Comment by MauriceBrg** [comment]
Since this is a step that is done by AWS I think it's highly unlikely that you can influence this.

What you could do in principle is store additional assets in S3, download them to `/tmp` and use them in your code. You'd need to do that at the start of the Lambda Execution, which will make your function run longer.

**Comment by izhangzhihao** [comment]
You are right. And if the plugin can help to split dependencies to two packages things will be much easier.
