### ISSUE TITLE
Minify dependencies

### ISSUE THREAD

**Issue by calclavia** [UnitedIncome/serverless-python-requirements#66]
It would be nice to have a feature to minify all modules dependencies. Some projects may find it helpful.

https://liftoff.github.io/pyminifier/

I realize the package I'm using (Tensorflow/Keras ML libraries) are quite large and don't fit well into 500MB `tmp/` space in AWS Lambda. Right now it's approximately ~540 MB, which is almost there!

**Comment by carlkibler** [comment]
Alternatively, you could build your own minified package and put that in your requirements.txt. Build 'minified-tensorflow' and push to S3. Then put that S3 URL into requirements instead of the pypi version. Actually, keep it on local filesystem too, so you don't have to re-download it!

You'd have to re-release it now and then, but ultimately that would be faster for you - doing pyminify on 500 MB of python packages must be pretty slow and you would pay that cost every time you repackage your function. Not to mention probably redownloading 500 MB of packages (not sure if the docker image caches this stuff? That would be cool).

I'm not saying minifying is a bad idea, just thinking out loud about an alternative that seems like it'd be faster for you.

**Comment by bsamuel-ui** [comment]
If the slimming option hasn't addressed this need, please feel free to reopen.
