### ISSUE TITLE
dockerizePip: true - standard_init_linux.go:185: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by chasebleyl** [UnitedIncome/serverless-python-requirements#94]
I am getting the following error when attempting to deploy:

`standard_init_linux.go:185: exec user process caused "exec format error"`

The *lambci/lambda* docker image is downloaded and up to date. 

I found the following on Stack Overflow but am unsure how this might apply, if at all: https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error.

Do you have any idea what I might be doing wrong here? I tried initially setting this up on my Windows machine, switched over to Linux, and am giving this a second go on Windows. Hopefully I can figure it out this time around.

**Comment by dschep** [comment]
huh.. that's very odd indeed. I'm afaid I've never run into this issue. I don't personally know anyone who uses this on windows, but I think some people do and it should work. I use it on 64bit Linux, so I don't usually use docker, but if I do I have to run `sls package` with `sudo` because I don't like to keep my user in the `docker` group (bc it pretty much makes your computer about as secure as running everythign as root), but my team mates use macs with docker.

**Comment by AlecBenzer** [comment]
On OSX I'm getting an error that seems like it *might* be related:

```
     docker: Error response from daemon: OCI runtime create
     failed: container_linux.go:296: starting container process
     caused "exec: \"nodejs4.3\": executable file not found 
     in $PATH": unknown.       
```

I'm just going off the fact that both are Docker errors involving exec.

OSX 10.13.2
Docker version 17.12.0-ce, build c97c6d6
serverless-python-requirements 3.3.0
serverless 1.13.0

I can reproduce the exact error running:

```
docker run -it --entrypoint=nodejs4.3 lambci/lambda:build-nodejs4.3 
```

I don't see where in the serverless-python-requirements code Docker might be getting invoked in this way though.

**Comment by dschep** [comment]
Ohh!! Your runtime is nodejs4.3 not python2.7 or python3.6. If you're doing that in combination with `package: individually` then I think #117 should handle this. Make sure you're using the latest version of this plugin since that was a relatively recent addition.

**Comment by AlecBenzer** [comment]
Yeah just realized this -- I'm not using `package: individually`, but I do have both python and node functions in the same serverless.yml. Is that supported? Do I need to just restrict the scope of th plugin somehow?

Also, I'm now less sure that this has anything to do with @chasebleyl's initial issue...

**Comment by AlecBenzer** [comment]
Yeah, the issue seems to be that https://github.com/UnitedIncome/serverless-python-requirements/blob/e77ef4aa1636acda10ce1c06f59445e9fd520b6c/index.js#L29 infers the python version from `provider.runtime`, and doesn't "see" that `functions.myfunc.runtime` is set to python3.6.

Setting:

```yml
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:python3.6
    pythonBin: python3.6
```

seems to address this.

**Comment by dschep** [comment]
Yup, that config should do the trick too. no idea what that error is tho 😕

**Comment by AlecBenzer** [comment]
Using the build image instead:

```yml
    dockerImage: lambci/lambda:build-python3.6
```

get me further (I think?) to this error:

```
Error: EEXIST: file already exists, symlink '<redacted>/.serverless/requiremen
ts/Flask-0.12.2.dist-info' -> './Flask-0.12.2.dist-info'
    at Object.fs.symlinkSync (fs.js:1034:18)                                          
    at fse.readdirSync.map (<redacted>/node_modules/serverless-python-requirem
ents/lib/link.js:44:13)
    at Array.map (<anonymous>)
    at ServerlessPythonRequirements.linkRequirements (<redacted>/node_modules/
serverless-python-requirements/lib/link.js:24:38)
From previous event:                                       
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:96:33)
    at runCallback (timers.js:756:18)                       
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:           
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:87:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
    at <anonymous>

**Comment by dschep** [comment]
You'll ahve to remove `Flask-0.12.2.dist-info` and other items from your service root that the plugin wants to link. I should probably update the `sls requirements clean` comand to do that too.

**Comment by AlecBenzer** [comment]
I'm not sure what you mean -- those files don't already exist in my directory. I.e., there is no `Flask-0.12.2.dist-info` in my CWD when I run `sls package`.

**Comment by dschep** [comment]
oh. huh. that's odd :confounded:

**Comment by miketheman** [comment]
Reviewing old issues, and this one appears to have been run with a version that still contained a `link.js` file - which has since been refactored and no longer exists, making it a little difficult to reproduce and validate.
I'm going to close this issue, however if this error is being surfaced with a recent version of the plugin, please open a new issue with the version details, and any error messages, file structures, so we can reproduce the error. Thanks!
